import React, { useState } from "react";
import Head from "next/head";
import Toggle from "../components/Toggle";
import { Grid, Section } from "../styles/shared";
import dataArr from "../data/data.json";
import Card from "../components/Card";

export default function Home() {
  const [isToggleActive, setIsToggleActive] = useState(false);
  return (
    <>
      <Head>
        <title>Pricing Comp. with toggle | FEM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <p>Annually</p>
        <Toggle
          isToggleActive={isToggleActive}
          setIsToggleActive={setIsToggleActive}
        />
        <p>Monthly</p>
      </Section>
      <Grid>
        {dataArr.map((data) => (
          <Card
            data={data}
            key={data.heading}
            isToggleActive={isToggleActive}
          />
        ))}
      </Grid>
    </>
  );
}
